# Generated by Django 5.2.8 on 2025-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorprofile",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="instructorprofile",
            name="hire_date",
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="name",
            field=models.CharField(default="exit", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="surname",
            field=models.CharField(default="empty", max_length=255),
            preserve_default=False,
        ),
    ]
