# Generated by Django 5.2.8 on 2025-11-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_degreelevel_remove_co_po_mapping_weight_and_more"),
        ("users", "0002_remove_instructorprofile_employee_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="instructorprofile",
            name="surname",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="surname",
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.program",
            ),
        ),
    ]
