# Generated by Django 5.2.8 on 2025-11-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("evaluation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="co_po_mapping",
            name="course_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluation.courseoutcome",
            ),
        ),
    ]
