# Generated by Django 5.2.8 on 2025-11-19 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                related_name="courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="co_po_mapping",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.department"
            ),
        ),
        migrations.AddField(
            model_name="programoutcome",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programoutcome",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.department"
            ),
        ),
        migrations.AddField(
            model_name="co_po_mapping",
            name="program_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.programoutcome"
            ),
        ),
        migrations.AddField(
            model_name="programoutcome",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.term"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.term"
            ),
        ),
        migrations.AddConstraint(
            model_name="co_po_mapping",
            constraint=models.UniqueConstraint(
                fields=("course", "course_outcome", "program_outcome"),
                name="unique_co_po_mapping",
            ),
        ),
    ]
