# Generated by Django 5.2.8 on 2025-11-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="co_po_mapping",
            name="weight",
        ),
        migrations.AddField(
            model_name="co_po_mapping",
            name="weight_percentage",
            field=models.FloatField(default=0, help_text="0.0 to 1.0"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "degree_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.degreelevel",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
            ],
        ),
    ]
